version: "3.9"
services:
  wayland-base:
    build:
      context: ./wayland-base
      dockerfile: Containerfile
      args:
        NAME: ${NAME}
        IMAGE_REGISTRY: ${IMAGE_REGISTRY}
        IMAGE_NAME: ${IMAGE_NAME}
        IMAGE_VERSION: ${IMAGE_VERSION}
        BASE_REGISTRY: ${BASE_REGISTRY}
        BASE_IMAGE: ${BASE_IMAGE}
        BASE_VERSION: ${BASE_VERSION}
        GPU: ${GPU}
        BASE_GPU: ${BASE_GPU}
    image: ${IMAGE_REGISTRY}${IMAGE_NAME}${GPU}:${IMAGE_VERSION}
