FROM ubuntu:latest as download-wic
ARG TORIZON_VERSION

RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y \
    curl \
    unzip

RUN curl -L -o torizon.zip https://github.com/commontorizon/meta-common-torizon/releases/download/${TORIZON_VERSION}/torizon-core-common-docker-dev-${TORIZON_VERSION}-qemux86-64.zip \
    && unzip torizon.zip -d /torizon \
    && rm torizon.zip \
    && mv /torizon/*.wic /torizon/torizon.wic

FROM ubuntu:latest as qemu

RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y \
        qemu-system \
        qemu-utils \
        qemu-system-common \
        isc-dhcp-server \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY --from=download-wic /torizon/torizon.wic .
COPY ./entry.sh /usr/bin/entry

COPY ./dhcpd.conf /etc/dhcp/dhcpd.conf

RUN chmod +x /usr/bin/entry

ENTRYPOINT [ "entry" ]
