# Copyright (c) 2023 Matheus Castello
# SPDX-License-Identifier: MIT
ARG BASE_REGISTRY=
ARG BASE_IMAGE=
ARG BASE_VERSION=
ARG GPU=

FROM ${BASE_REGISTRY}${BASE_IMAGE}:${BASE_VERSION} AS builder

# install build dependencies, autotools and wayland dev
RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y \
        git \
        build-essential \
        autoconf \
        automake \
        libtool \
        pkg-config \
        libgtk-3-dev \
        libwayland-dev \
    && apt-get clean

# clone the repo and build
WORKDIR /immodule
RUN git clone https://gitlab.com/microhobby/gtk-wayland-textinputv1.git && \
    cd gtk-wayland-textinputv1 && \
    ./autogen.sh && \
    ./configure && \
    make

FROM ${BASE_REGISTRY}${BASE_IMAGE}${GPU}:${BASE_VERSION} AS wayland-base

ARG BASE_REGISTRY
ARG BASE_IMAGE
ARG BASE_VERSION
ARG GPU

COPY --from=builder /immodule/gtk-wayland-textinputv1/src/.libs/im-wltextinputv1.so /immodules/im-wltextinputv1.so

# GTK to rule the world
RUN apt-get -y update && apt-get install -y \
        libgtk-3-0 \
    && apt-get clean && apt-get autoremove && rm -rf /var/lib/apt/lists/*

# fixup the immodule path and update the cache
RUN ARCH=$(arch) && \
    IMAGE_ARCH="$(arch)" && \
    if [ "${ARCH}" = "x86_64" ]; then \
        LIB_ARCH="x86_64-linux-gnu" ; \
    fi && \
    if [ "${IMAGE_ARCH}" = "aarch64" ]; then \
        LIB_ARCH="aarch64-linux-gnu" ; \
    fi && \
    if [ "${IMAGE_ARCH}" = "armv7l" ]; then \
        LIB_ARCH="arm-linux-gnueabihf" ; \
    fi && \
    mv /immodules/im-wltextinputv1.so /usr/lib/$LIB_ARCH/gtk-3.0/3.0.0/immodules/im-wltextinputv1.so && \
    /usr/lib/$LIB_ARCH/libgtk-3-0/gtk-query-immodules-3.0 --update-cache
