# Copyright (c) 2023 Matheus Castello
# SPDX-License-Identifier: MIT

ARG BASE_REGISTRY=
ARG BASE_IMAGE=
ARG BASE_VERSION=

FROM ${BASE_REGISTRY}${BASE_IMAGE}:${BASE_VERSION} AS Build

ARG BASE_REGISTRY=
ARG BASE_IMAGE=
ARG BASE_VERSION=

ARG UPTANE_SIGN_VERSION=2.0.2

USER root

# Repo for setup
# JDK for OSTree push
# Vim for convenience
RUN apt-get update && apt-get install --no-install-recommends --no-install-suggests -y \
    curl \
    default-jre \
    vim \
    nano \
    git-lfs \
    python3-gi \
    python3-pip \
    gir1.2-ostree-1.0 \
    jq \
    unzip \
    ostree \
    wget \
    openjdk-11-jre-headless \
    pkg-config \
    libcairo2-dev \
    && rm -rf /var/lib/apt/lists/*

# Install repo
RUN curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > /bin/repo && chmod a+x /bin/repo

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.9 1
RUN update-alternatives --config python

# Install Github Runner dependencies
RUN curl -s -O -L https://raw.githubusercontent.com/actions/runner/main/src/Misc/layoutbin/installdependencies.sh
RUN chmod +x ./installdependencies.sh && ./installdependencies.sh && \
    rm -rf /var/lib/apt/lists/* && rm ./installdependencies.sh

# Github Runner setup script
COPY start.sh /usr/bin/
RUN chmod +x /usr/bin/start.sh

# Install AWS CLI tool
RUN curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip && ./aws/install && rm -rf awscliv2.zip ./aws

# OSTree promotion script
COPY ostree-repo-promotion.py /usr/bin
RUN chmod +x /usr/bin/ostree-repo-promotion.py

# Add scripts for delegation publishing
COPY requirements.txt /tmp
RUN pip3 install --no-cache-dir -r /tmp/requirements.txt \
    && rm -rf /tmp/requirements.txt

COPY create-delegations-from-ostree-repo.py /usr/bin
RUN chmod +x /usr/bin/create-delegations-from-ostree-repo.py
COPY sign-and-push-delegations.sh /usr/bin
RUN chmod +x /usr/bin/sign-and-push-delegations.sh

RUN wget https://github.com/uptane/ota-tuf/releases/download/v${UPTANE_SIGN_VERSION}/cli-${UPTANE_SIGN_VERSION}.tgz -P /tmp \
    && tar xvf /tmp/cli-${UPTANE_SIGN_VERSION}.tgz -C /tmp \
    && cp -a /tmp/uptane-sign/lib/. /usr/lib/ \
    && mv /tmp/uptane-sign/bin/uptane-sign /usr/bin/uptane-sign \
    && rm /tmp/cli-${UPTANE_SIGN_VERSION}.tgz \
    && rm -rf /tmp/uptane-sign

USER usersetup
