# Copyright (c) 2023 Matheus Castello
# SPDX-License-Identifier: MIT

ARG IMAGE_ARCH=
ARG BASE_REGISTRY=
ARG BASE_IMAGE=
ARG BASE_VERSION=

FROM ${BASE_REGISTRY}${BASE_IMAGE}:${BASE_VERSION} AS SDK

# Make sure we don't get notifications we can't answer during building.
ENV DEBIAN_FRONTEND="noninteractive"

# stick to bookworm on /etc/apt/sources.list.d
RUN sed -i 's/sid/bookworm/g' /etc/apt/sources.list.d/debian.sources

# update the base packages
RUN apt-get -y update && apt-get install -y --no-install-recommends \
    apt-utils \
    && apt-get -y upgrade \
    && apt-get clean && apt-get autoremove && rm -rf /var/lib/apt/lists/*

# Add the mono feed
RUN apt-get -q -y update && \
    apt install apt-transport-https dirmngr gnupg ca-certificates && \
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 \
    --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF && \
    echo "deb https://download.mono-project.com/repo/debian preview-buster main" \
    | tee /etc/apt/sources.list.d/mono-official-preview.list

# install dependencies
RUN apt-get -y update && apt-get install -y --no-install-recommends \
    curl \
    gettext \
    apt-transport-https \
	libunwind-13 \
    icu-devtools \
	libfontconfig1 \
    libgtk2.0-0 \
	libdrm2 \
	libinput10 \
    libdigest-md5-perl \
    libssl3 \
    openssl \
    openssh-server \
    rsync \
    file \
    mono-complete \
	&& apt-get clean && apt-get autoremove && rm -rf /var/lib/apt/lists/*

# fix mime types
RUN apt-get -y update && apt-get --reinstall install -y --no-install-recommends \
    shared-mime-info \
	&& apt-get clean && apt-get autoremove && rm -rf /var/lib/apt/lists/*
