# Copyright (c) 2023 Matheus Castello
# SPDX-License-Identifier: MIT

ARG REGISTRY=
ARG IMAGE_ARCH=
ARG BASE_REGISTRY=
ARG BASE_IMAGE=
ARG BASE_VERSION=
ARG BASE_VERSION2=
ARG BASE_IMAGE2=
ARG GPU=

FROM ${BASE_REGISTRY}${BASE_IMAGE}-${IMAGE_ARCH}:${BASE_VERSION} AS SDK

ARG REGISTRY
ARG IMAGE_ARCH
ARG BASE_REGISTRY
ARG BASE_IMAGE
ARG BASE_VERSION
ARG BASE_VERSION2
ARG BASE_IMAGE2
ARG GPU

LABEL org.opencontainers.image.source https://github.com/commontorizon/Containerfiles
LABEL org.opencontainers.image.authors "microhobby <matheus@castello.eng>"
LABEL org.opencontainers.image.title "Debian Cross Toolchain"
LABEL org.opencontainers.image.description "Image with toolchain for cross-compiling"
LABEL org.opencontainers.image.licenses "MIT"
