# Copyright (c) 2024 Matheus Castello
# SPDX-License-Identifier: MIT
ARG NAME
ARG IMAGE_ARCH=
ARG BASE_REGISTRY=
ARG BASE_IMAGE=
ARG BASE_VERSION=
ARG GPU=
ARG DOTNET_SEMVER=

# TODO: in sync with https://github.com/torizon/torizon-containers/blob/stable/debian-dotnet-development-images/base/Dockerfile

FROM ${BASE_REGISTRY}${BASE_IMAGE}${GPU}:${BASE_VERSION} AS dotnet-upstream

ARG NAME
ARG IMAGE_ARCH
ARG BASE_REGISTRY
ARG BASE_IMAGE
ARG BASE_VERSION
ARG GPU
ARG DOTNET_SEMVER
ARG TARGETARCH

ENV DEBIAN_FRONTEND="noninteractive"

RUN apt-get update && apt-get install -y \
    --no-install-recommends --no-install-suggests \
    curl \
    ca-certificates \
    && apt-get clean && apt-get autoremove \
    && rm -rf /var/lib/apt/lists/*

RUN curl -L -o /dotnet-install.sh https://dot.net/v1/dotnet-install.sh \
    && chmod a+x /dotnet-install.sh \
    && mkdir dotnet

WORKDIR /dotnet

RUN /dotnet-install.sh \
    --install-dir /dotnet \
    --runtime dotnet \
    --version ${DOTNET_SEMVER} \
    --os linux \
    --architecture ${TARGETARCH} \
    --no-path

FROM ${BASE_REGISTRY}${BASE_IMAGE}${GPU}:${BASE_VERSION} AS dotnet-release

ARG NAME
ARG IMAGE_ARCH
ARG BASE_REGISTRY
ARG BASE_IMAGE
ARG BASE_VERSION
ARG GPU
ARG DOTNET_SEMVER

ENV DOTNET_ROOT=/dotnet
ENV PATH=$PATH:/dotnet

RUN apt-get update && apt-get install -y \
    --no-install-recommends --no-install-suggests \
    libicu72 \
    libssl3 \
    && apt-get clean && apt-get autoremove \
    && rm -rf /var/lib/apt/lists/*

COPY --from=dotnet-upstream /dotnet /dotnet
