# Copyright (c) 2024 Matheus Castello
# SPDX-License-Identifier: MIT

ARG NAME=
ARG REGISTRY=
ARG IMAGE_ARCH=
ARG BASE_REGISTRY=
ARG BASE_IMAGE=
ARG BASE_VERSION=
ARG BASE_VERSION2=
ARG BASE_IMAGE2=
ARG GPU=

# TODO: maintain in sycn with https://github.com/torizon/torizon-containers/blob/stable/debian-docker-images/imx/qt6-wayland/Dockerfile

FROM ${BASE_REGISTRY}${BASE_IMAGE}${GPU}:${BASE_VERSION} AS WAYLAND

ARG NAME
ARG REGISTRY
ARG IMAGE_ARCH
ARG BASE_REGISTRY
ARG BASE_IMAGE
ARG BASE_VERSION
ARG BASE_VERSION2
ARG BASE_IMAGE2
ARG GPU

COPY kms-setup.sh /usr/bin/kms-setup.sh

RUN apt-get -y update && apt-get install -y --no-install-recommends \
    apt-utils \
    && apt-get -y upgrade \
    && apt-get clean && apt-get autoremove && rm -rf /var/lib/apt/lists/*

# Install remaining dependencies required to run qtbase
RUN apt-get -y update && apt-get install -y --no-install-recommends \
       libqt6gui6 \
       libfontconfig1-dev \
       libqt6concurrent6 \
       libqt6dbus6 \
       libqt6network6 \
       libqt6printsupport6 \
       libqt6sql6 \
       libqt6test6 \
       libqt6widgets6 \
       libqt6xml6 \
       libqt6qml6 \
       libqt6opengl6 \
       libqt6quicktest6 \
       libqt6quickwidgets6 \
       qt6-wayland \
       && apt-get clean && apt-get autoremove && rm -rf /var/lib/apt/lists/*

ENV QT_QPA_PLATFORM="wayland"

# EGLFS configuration
ENV QT_QPA_EGLFS_INTEGRATION="eglfs_kms"
ENV QT_QPA_EGLFS_KMS_ATOMIC="1"
ENV QT_QPA_EGLFS_KMS_CONFIG="/etc/kms.conf"
