# Copyright (c) 2023 Matheus Castello
# SPDX-License-Identifier: MIT
ARG NAME
ARG IMAGE_ARCH=
ARG BASE_REGISTRY=
ARG BASE_IMAGE=
ARG BASE_VERSION=
ARG GPU=
ARG BASE_GPU=

FROM ${BASE_REGISTRY}${BASE_IMAGE}${BASE_GPU}:${BASE_VERSION} AS weston-upstream

FROM ${BASE_REGISTRY}${BASE_IMAGE}${BASE_GPU}:${BASE_VERSION} AS weston-am62

FROM ${BASE_REGISTRY}${BASE_IMAGE}${BASE_GPU}:${BASE_VERSION} AS weston-imx8

ARG NAME
ARG IMAGE_ARCH
ARG BASE_REGISTRY
ARG BASE_IMAGE
ARG BASE_VERSION
ARG GPU
ARG BASE_GPU

# get the image that is needed for this one
FROM weston-${NAME} AS weston

COPY ./conf/weston.ini /etc/xdg/weston/weston.ini
COPY ./conf/weston-dev.ini /etc/xdg/weston-dev/weston.ini
COPY entry.sh /usr/bin/entry.sh
COPY imx8.deb /imx8.deb

RUN if [ "$NAME" = "imx8" ]; then \
    chmod +x /usr/bin/entry.sh && \
    apt-get update && \
    apt-get install -y \
    --allow-downgrades \
    /imx8.deb \
    libgl-dev && \
    apt-get --fix-broken install && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean; \
    fi

RUN rm /imx8.deb
